apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-app
        image: vivek8076/myproject1:v3
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-service:27017/mydb